app/models.py
from sqlalchemy import ForeignKey
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitches',backref = 'pitcher',lazy = "dynamic")
    comments_id = db.relationship('Comments', backref = 'commenter', lazy ='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password) :
        self.pass_secure = generate_password_hash(password) 

    def verify_password(self,password):
        return check_password_hash(self.pass_secure, password)     

    def __repr__(self):
        return f'User{self.username}'
    
class Role(db.Model):
    __tablename__ = 'role'  

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref ='role', lazy = 'dynamic')

    def __repr__(self):
        return f'User {self.name}'

class Pitches(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments_id = db.relationship('Comments', backref = 'comments', lazy ='dynamic')
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit() 

    @classmethod    
    def get_pitch (cls, id):
        pitches = Pitches.query.filter_by(user_id = id).all()
        return pitches

class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime,default=datetime.utcnow)
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls, id) :
        comments = Comments.query.filter_by(pitch_id = id).all()
        return comments  

class Category(db.Model) :
    __tablename__ = 'category'

    id = db.Column(db.Integer, primary_key = True)
    category = db.Column(db.String(255))
    pitch_id = db.relationship('Pitches', backref = 'categories', lazy = 'dynamic')

app/main/forms.py
from unicodedata import category
import flask_simplemde
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField , SelectField
from wtforms.validators import DataRequired

class UpdateProfile(FlaskForm):
    bio = TextAreaField("Tell us something about yourself", validators=[DataRequired()])
    submit = SubmitField('Submit')

class PitchesForm(FlaskForm):

    title = StringField('Pitch title', validators=[DataRequired()])
    category = SelectField("Category", choices =[(1,'Technology'),(2,'Fitness'),(3,'Interview'),(4,'Product pitch')],validators=[DataRequired()])
    content = TextAreaField('Write your pitch', validators=[DataRequired()])
    submit = SubmitField('Submit')    

class CommentsForm(FlaskForm):
    comment = TextAreaField('Write your comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos', IMAGES)
mail = Mail()
simple = SimpleMDE()

#Initializing the application

def create_app(config_name):
    app = Flask(__name__)

    #Creating the app configurations
    app.config.from_object(config_options[config_name])

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    #Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

     #Registering auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    #configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import redirect, render_template, url_for, abort,request
from flask_login import current_user, login_required
from . import main
from ..models import Comments, User, Pitches, Category
from .forms import UpdateProfile, PitchesForm, CommentsForm
from .. import db, photos
import markdown2

@main.route('/')
def index():
    pitches = Pitches.query.all()
    return render_template('index.html', pitches = pitches, pitcher = pitches)

@main.route('/user/<uname>') 
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    pitches = Pitches.get_pitch(user.id)

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user = user, pitches = pitches)    

@main.route('/user/<uname>/update', methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    
    if user is None:
        abort(404)

    form = UpdateProfile() 
    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()  

        return redirect(url_for('.profile', uname = user.username)) 
    return render_template('profile/update_profile.html', form = form)

@main.route('/user/<uname>/update/pic', methods=['POST']) 
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first() 
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile',uname=uname))  

@main.route('/user/pitch/new/<int:id>', methods =['GET', 'POST'])
@login_required
def new_pitch(id):
    form = PitchesForm()
    user = User.query.filter_by(id = id).first()

    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        category = form.category.data
        pitch_category = Category.query.filter_by(id = category).first()
        new_pitch = Pitches(title = title, content = content, pitcher = current_user, categories = pitch_category)
        new_pitch.save_pitch()
        return redirect(url_for('.profile', uname = user.username ))

    return render_template('new_pitch.html', pitch_form = form, user = user.username)

@main.route('/user/comment/new/<int:id>', methods =["GET", "POST"])
@login_required
def comment(id):
    form = CommentsForm()
    comments = Comments.query.filter_by(pitch_id = id).all()
    pitch = Pitches.query.filter_by(id = id).first()

    if form.validate_on_submit():
        comment_submitted = form.comment.data
        new_comment = Comments(comment= comment_submitted, commenter = current_user, comments = pitch )
        new_comment.save_comment()

    return render_template('new_comments.html', comment_form = form, comments = comments, pitch = pitch)  

@main.route('/category/<int:id>')  
def category(id) :
    pitches = Pitches.query.filter_by(category_id = id).all()

    return render_template('category.html', categories = pitches)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pitch-Hub</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>
<body>
    {% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
{% endblock %}
<!-- <div class="container-fluid bg-dark footer fixed-bottom">
        
    <p class="text-center text-white  mt-4 pt-4">
        &copy; Copyright 2022, Ruweydha Abdinoor
    </p>

  </div> -->
</body>
</html>

app/templates/category.html
{% extends 'base.html' %}
{% block content %}
{% if categories %}
<h1 class="text-center" style="color: #023047 ;">Pitches</h1>
{% for pitch in categories %}
    
    <div class="row">
        <div class="card " style="width: 70%; border-left: none; border-right: none; margin: auto; background-color: #cfdbd5;">
            <div class="card-body">
              <h5>{{pitch.content}}</h5>
              <a href="/user/comment/new/{{pitch.id}}" style="text-decoration: none; color: #e76f51; font-weight: 600;">Comment</a>
            </div>
          </div>
        
    </div>
{% endfor %}
{% else %}
<h4 class="mt-2" style="color: #023047">No pitches submitted yet</h4>
{% endif %}
<div class="text-center mt-3">
    <button class="btn btn-secondary btn-md"><a href="/user/pitch/new/{{current_user.id}}" style="text-decoration: none; color: white;">Write new pitch</a></button>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}

  {% if pitches %}
<div class="container mb-5 pb-5" style="color: #023047;">
  <h1 class="text-center">All pitches</h1>
  <p class="text-center" style="font-weight: 500;"><em>At pitch-hub we love to hear your pitches and our users can give you feedback.</em></p>
      <div class="row">
        <div class="col-md-12">
          {% for pitch in pitches %}
          <div class="card mt-3" style="width: 70%; border-left: none; border-right: none;">
            <div class="card-body d-flex justify-content-between">
              <div>
                <h5 class="text-center">{{pitch.pitcher.username}}</h5>
              <p class="card-text">{{pitch.content}}</p>
              </div>
              <div>
                <p class="card-text">{{pitch.date_posted.strftime('%Y-%m-%d')}}</p>
                <button  class="btn btn-secondary btn-sm"><a style="color: #fff; text-decoration: none;" href="/user/comment/new/{{pitch.id}}" class="card-link">Comment</a></button>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
  </div>
{% endif %}

{% endblock %}

app/templates/navbar.html
  <nav class="navbar navbar-expand-lg navbar-light bg-dark" >
    <div class="container-fluid" >
      <a class="navbar-brand" href="/" style="color: #fb8500;">Pitch-Hub</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" style="color: #fff;" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color: #fff;" href="/category/1">Technology</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color: #fff;" href="/category/2">Fitness</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color: #fff;" href="/category/3">Interview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color: #fff;" href="/category/4">Product Pitch</a>
          </li>
         <div class="right" style="margin-left: 500px;">
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color: #fff;" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{current_user.username}}
            </a>
            <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
              <li><a class="dropdown-item" href="{{url_for('auth.logout')}}">Sign Out</a></li>
              <li><hr class="dropdown-divider"></li>
              <li>
                {% if user == current_user %}
                <a class="dropdown-item" href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
                {% endif %}
              </li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" style="color: white;" href="{{url_for('auth.login')}}">Sign in</a>
          </li>
          {% endif %}
         </div>
        </ul>
      </div>
    </div>
  </nav>
  

app/templates/new_comments.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content%}
  <div class="container">
      <div class="col-md-8 mt-3">
          {{ wtf.quick_form(comment_form) }}
          {{simplemde.load}}
      </div>
  </div>
<h1 class="text-center">{{pitch.content}}</h1>
  {% if comments %}
  {% for comment in comments %}
  <div class="card " style="width: 70%; height: 50px; border-left: none; border-right: none; margin: auto; background-color: #cfdbd5;">
    <div class="card-body">
      <p style="font-weight: 600;">{{comment.comment}}</p>
    </div>
  </div>
  {% endfor %}
  {% endif %}

{% endblock %}  

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content%}
  <div class="container mt-3">
      <div class="col-md-8">
          {{ wtf.quick_form(pitch_form) }}
          {{simplemde.load}}
      </div>
  </div>

{% endblock %}  

app/templates/profile/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">

            <div class="col-md-3">
                {% if user.profile_pic_path %}
                <img src="{{url_for('static', filename = user.profile_pic_path)}}" style="width: 300px; height: 300px; border-radius: 500%;"  alt="" class="img-fluid">
                {% else %}
                <p style="color: #023047;" class="mt-5">No profile picture</p>
                {% endif %}
             </div>
    
            <div class="col-md-2 pt-5">
                <h2 style ="color: #023047;">{{user.username | capitalize}}</h2>
                {% if user.bio %}
                <p style="color: #023047;">{{user.bio}}</p>
                {% else %}
                <p style="color: #023047;">{{user.username | capitalize}} Has no bio</p>
                {% endif %}

            </div>
            <div class="col-md-7 pt-5">
                {% if user == current_user %}
                <div class="col-md-6">
                    {% if user.profile_pic_path %}
                    <h3 style="color: #023047;">Change profile Picture</h3>
                    {% else %}
                    <h3 style="color: #023047;">Add profile picture</h3>
                    {% endif %}
                    <form action="{{url_for('main.update_pic', uname = user.username)}}" method="post" enctype="multipart/form-data">
                        <input type="file" name="photo" class="form-control" required>
                        <input class="mt-2" type="submit">
                    </form>
                </div>
            {% endif %}
            </div>
    
    </div>
    <div class="row">
       
    </div>
    <div class="row">
        <h1 class="text-center mt-3" style="color: #023047 ;" >Pitches</h1>
        {% if pitches %}
        {% for pitch in pitches %}
        <div class="card " style="width: 70%; border-left: none; border-right: none; margin: auto; background-color: #cfdbd5;">
            <div class="card-body">
              <p>{{pitch.content}}</p>
            </div>
          </div>
        
        {% endfor %}
        {% else %}
        <h3>You have no pitches yet</h3>
        {% endif %}
        <div class="text-center mt-3">
            <button class="btn btn-secondary"><a href="/user/pitch/new/{{user.id}}" style="color: white; text-decoration: none;">Write new pitch</a></button>
        </div>
        

    </div>
</div>
{% endblock %}

app/templates/profile/update_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container mt-3">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}